# PAGECAMEL  (C) 2008-2018 Rene Schickbauer
# Developed under Artistic license
package PageCamel::Worker::PostfixCommands;
#---AUTOPRAGMASTART---
use 5.020;
use strict;
use warnings;
use diagnostics;
use mro 'c3';
use English qw(-no_match_vars);
use Carp;
our $VERSION = 2;
use Fatal qw( close );
use Array::Contains;
#---AUTOPRAGMAEND---

use base qw(PageCamel::Worker::BaseModule);
use PageCamel::Helpers::DateStrings;
use WWW::Mechanize::GZip;
use PageCamel::Helpers::DBSerialize qw/dbderef/;

use Readonly;

sub new {
    my ($proto, %config) = @_;
    my $class = ref($proto) || $proto;
    
    my $self = $class->SUPER::new(%config); # Call parent NEW
    bless $self, $class; # Re-bless with our class

    my %commands;

    foreach my $cmd (qw[POSTFIX_UPDATE_ALIASES]) {
        my $cmdfunc = "do_" . lc($cmd);
        $commands{$cmd} = $cmdfunc;
    }
    $self->{extcommands} = \%commands;

    return $self;
}

sub reload {
    my ($self) = shift;
    # Nothing to do.. in here, we are pretty much self contained
    return;
}

sub register {
    my $self = shift;

    # Register ourselfs in the RBSCommands module with additional commands
    my $comh = $self->{server}->{modules}->{$self->{commands}};
    
    foreach my $cmd (sort keys %{$self->{extcommands}}) {
        $comh->register_extcommand($cmd, $self);
    }
    return;
}

sub execute {
    my ($self, $command, $arguments) = @_;
    
    if(defined($self->{extcommands}->{$command})) {
        my $cmdfunc = $self->{extcommands}->{$command};
        return $self->$cmdfunc($arguments);
    }
    return;
}

sub do_postfix_update_aliases {
    my ($self, $arguments) = @_;

    my $dbh = $self->{server}->{modules}->{$self->{db}};
    my $reph = $self->{server}->{modules}->{$self->{reporting}};
    $reph->debuglog("Generating new /etc/aliases file");

    my $selsth = $dbh->prepare_cached("SELECT * FROM postfix_aliases
                                        ORDER BY can_autodelete, realname, aliasname")
            or croak($dbh->errstr);
    $selsth->execute or croak($dbh->errstr);
    my @lines;
    push @lines, "##########################################";
    push @lines, "# DO NOT EDIT - AUTO-GENERATED BY PAGECAMEL #";
    push @lines, "##########################################";
    push @lines, "";
    push @lines, "# Static (non-autodelete) entries";
    my $foundautodelete = 0;
    while((my $line = $selsth->fetchrow_hashref)) {
        if(!$foundautodelete && $line->{'can_autodelete'}) {
            $foundautodelete = 1;
            push @lines, "";
            push @lines, "# Dynamic (autodelete) entries";
        }
        push @lines, $line->{aliasname} . ':   ' . $line->{realname};
    }
    $selsth->finish;
    $dbh->rollback;
    open(my $ofh, '>', '/etc/aliases') or croak($!);
    foreach my $line (@lines) {
        print $ofh $line, "\n";
    }
    close $ofh;
    $reph->debuglog("Running /usr/bin/newaliases");
    `/usr/bin/newaliases`;
    $reph->debuglog("*** Mail aliases updated ***");

    my $logtype = "OTHER"; # make logging visible only to admin user

    return (1, $logtype);
}


1;
__END__

=head1 NAME

PageCamel::Worker::BackupCommand - database backup command module

=head1 SYNOPSIS

This module does PostgreSQL database backups.

=head1 DESCRIPTION

This module is a plugin module for the "Commands" module and handles
PostgreSQL backups.

=head1 Configuration

    <module>
        <modname>backupcommand</modname>
        <pm>BackupCommand</pm>
        <options>
            <db>maindb</db>
            <memcache>memcache</memcache>
            <commands>commands</commands>
            <reporting>reporting</reporting>
            <pgdump>/usr/bin/pg_dump</pgdump>
            <basedir>/path/to/backups</basedir>
            <host>localhost</host>
            <port>5432</port>
            <username>postgres</username>
            <database>RBS_DB</database>
            <sudouser>someusername</sudouser>
        </options>
    </module>



=head2 execute

Callback to run a command.

=head2 do_backup

Internal function, call the external pg_dump command to execute a full database backup.

=head1 Dependencies

This module depends on the following modules beeing configured (the 'as "somename"'
means the key name in this modules configuration):

PageCamel::Worker::PostgresDB as "db"
PageCamel::Worker::Memcache as "memcache"
PageCamel::Worker::Commands as "commands"
PageCamel::Worker::Reporting as "reporting"

=head1 SEE ALSO

PageCamel::Worker

=head1 AUTHOR

Rene Schickbauer, E<lt>pagecamel@cavac.atE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2008-2011 by Rene Schickbauer

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.10.0 or,
at your option, any later version of Perl 5 you may have available.

=cut
